Rails.application.config.assets.precompile += %w( default/all.css )
Rails.application.config.assets.precompile += %w( default/all.js )

Rails.application.config.assets.precompile += %w( weareyvr/all.css )
Rails.application.config.assets.precompile += %w( weareyvr/all.js )

Rails.application.config.assets.precompile += %w( ArnhemPro-Blond.woff )
Rails.application.config.assets.precompile += %w( ArnhemPro-Blond.ttf )
Rails.application.config.assets.precompile += %w( ArnhemPro-BlondItalic.woff )
Rails.application.config.assets.precompile += %w( ArnhemPro-BlondItalic.ttf )
Rails.application.config.assets.precompile += %w( ArnhemPro-SemiBold.woff )
Rails.application.config.assets.precompile += %w( ArnhemPro-SemiBold.ttf )
Rails.application.config.assets.precompile += %w( ArnhemPro-SemiBoldItalic.woff )
Rails.application.config.assets.precompile += %w( ArnhemPro-SemiBoldItalic.ttf )
Rails.application.config.assets.precompile += %w( Fort-Extralight.otf )
Rails.application.config.assets.precompile += %w( Fort-ExtralightItalic.otf )
Rails.application.config.assets.precompile += %w( Fort-Book.otf )
Rails.application.config.assets.precompile += %w( Fort-BookItalic.otf )
Rails.application.config.assets.precompile += %w( Fort-Bold.otf )
Rails.application.config.assets.precompile += %w( Fort-BoldItalic.otf )
