@auth0 @javascript
Feature: Claim user profile
  In order to have a profile
  As a visitor
  I want to claim my autogenerated profile

  Background:
    Given there is a user available

  Scenario: Visitor claims profile
    When I visit the user profile page for "Example User"
    And I claim the user profile
    And I login with "Twitter"
    And I submit an email address
    Then I should own the profile
