# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baa5076fabe6896899de467479b83c30dbff2e3035f2096ac03587903859670f73337e39a9f63f768fa96105950af8cac24b4e28ecebf7d4e0248b9a006c41c9

test:
  secret_key_base: baa5076fabe6896899de467479b83c30dbff2e3035f2096ac03587903859670f73337e39a9f63f768fa96105950af8cac24b4e28ecebf7d4e0248b9a006c41c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  startup_genome_auth_code: <%= ENV["STARTUP_GENOME_AUTH_CODE"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_callback_url: <%= ENV["AUTH0_CALLBACK_URL"] %>
  auth0_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
